plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    runs {
        configureEach {
            mods {
                fishingmod {
                    source sourceSets.main
                }
            }
        }
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }
        server {
            workingDirectory project.file('run/server')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : project.minecraft_version,
            forge_version          : project.forge_version,
            mod_id                 : project.mod_id,
            mod_name               : project.mod_name,
            mod_license            : project.mod_license,
            mod_version            : project.mod_version,
            mod_authors            : project.mod_authors,
            mod_description        : project.mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}
